services:
  db:
    image: mariadb:10.3
    container_name: mariadb
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-database}
      MARIADB_USER: ${MARIADB_USER:-user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    ports:
      - ${MARIADB_PORT:-3306}:3306
    volumes:
      - db_data:/var/lib/mysql
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: on-failure
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025

volumes:
  db_data:
