services:
  goapp:
    container_name: go-supermarket
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    tty: true
    environment:
      - DB_USER=${MARIADB_USER:-user}
      - DB_PASSWORD=${MARIADB_PASSWORD:-password}
      - DB_NAME=${MARIADB_DATABASE:-database}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${MARIADB_PORT:-3306}
      - MAIL_SERVER=${MAIL_SERVER:-mailpit}
      - MAIL_PORT=${MAIL_PORT:-1025}
      - MAIL_SENDER=${MAIL_SENDER:-noreply@grocery-store.online}
    volumes:
      - ./production_data/pdfs:/app/orders_pdf:rw
      - ./production_data/csvs:/app/csv:rw
  db:
    image: mariadb:10.3
    container_name: mariadb
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-database}
      MARIADB_USER: ${MARIADB_USER:-user}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    ports:
      - ${MARIADB_PORT:-3306}:3306
    volumes:
      - db_data:/var/lib/mysql
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: on-failure
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025

volumes:
  db_data:
#//AZEVEDO-DA-SILVA, A. (2024) GO-PROJECT-1. [Source code] https://github.com/DestCom-Student-Projects/GO-PROJECT-1
